<?php require_once __DIR__.'/../config/database.php'; require_once __DIR__.'/../includes/functions.php'; require_login(); $vars=$pdo->query('SELECT * FROM variables ORDER BY id')->fetchAll(); require_once __DIR__.'/../includes/header.php'; ?>
<div class="container px-3 px-lg-4">
    <div class="d-flex flex-column flex-lg-row justify-content-between gap-3 mb-4"><div><div class="consult-step mb-2"><span>1</span> Input fakta lapangan</div><h2 class="section-title mb-1">Konsultasi Potensi Banjir</h2><p class="text-muted mb-0">Pilih satu gejala untuk setiap variabel. Nama field backend tetap: location, notes, dan symptom[variable_id].</p></div><a class="btn btn-outline-primary align-self-start" href="<?=app_url('laporan/index.php')?>"><i class="bi bi-clock-history me-2"></i>Riwayat</a></div>
    <form class="card p-4" method="post" action="proses.php"><?=csrf_field()?>
        <div class="row g-3 mb-3"><div class="col-lg-8"><label class="form-label fw-semibold">Lokasi Pengamatan</label><input name="location" class="form-control" placeholder="Contoh: Kelurahan Sukamaju, RT 03" required></div><div class="col-lg-4"><label class="form-label fw-semibold">Status</label><div class="alert alert-primary rounded-4 mb-0 py-2"><i class="bi bi-info-circle me-2"></i>Siap diproses mesin pakar</div></div></div>
        <div class="row g-3"><?php foreach($vars as $i=>$v): $st=$pdo->prepare('SELECT * FROM symptoms WHERE variable_id=? ORDER BY id'); $st->execute([$v['id']]); ?><div class="col-md-6 col-xl-4"><div class="symptom-card"><label class="form-label fw-bold"><span class="badge text-bg-primary rounded-pill me-2"><?=e($v['code'])?></span><?=e($v['name'])?></label><select class="form-select" name="symptom[<?=$v['id']?>]" required><?php foreach($st->fetchAll() as $s): ?><option value="<?=$s['id']?>"><?=e($s['code'])?> - <?=e($s['name'])?></option><?php endforeach; ?></select><small class="text-muted d-block mt-2"><?=e($v['description'] ?? '')?></small></div></div><?php endforeach; ?></div>
        <label class="form-label fw-semibold mt-4">Catatan Tambahan</label><textarea class="form-control" name="notes" rows="4" placeholder="Catatan kondisi sekitar, dokumentasi, atau informasi warga..."></textarea>
        <div class="d-flex flex-wrap gap-2 mt-4"><button class="btn btn-primary btn-lg"><i class="bi bi-cpu me-2"></i>Proses Forward Chaining</button><button type="reset" class="btn btn-outline-secondary btn-lg">Reset</button></div>
    </form>
</div>
<?php require_once __DIR__.'/../includes/footer.php'; ?>
