CREATE DATABASE IF NOT EXISTS sistem_pakar_banjir CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE sistem_pakar_banjir;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS activity_logs,diagnosis_results,consultation_details,consultations,rule_conditions,rules,symptoms,variables,users,roles,`references`;
SET FOREIGN_KEY_CHECKS=1;
CREATE TABLE roles(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(30) NOT NULL UNIQUE,description VARCHAR(120));
CREATE TABLE users(id INT AUTO_INCREMENT PRIMARY KEY,role_id INT NOT NULL,name VARCHAR(100) NOT NULL,email VARCHAR(120) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,is_active TINYINT(1) DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(role_id) REFERENCES roles(id));
CREATE TABLE variables(id INT AUTO_INCREMENT PRIMARY KEY,code VARCHAR(5) NOT NULL UNIQUE,name VARCHAR(80) NOT NULL,description TEXT);
CREATE TABLE `references`(id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(180) NOT NULL,source VARCHAR(180),description TEXT);
CREATE TABLE symptoms(id INT AUTO_INCREMENT PRIMARY KEY,variable_id INT NOT NULL,code VARCHAR(10) NOT NULL UNIQUE,name VARCHAR(120) NOT NULL,category VARCHAR(80) NOT NULL,description TEXT,reference_id INT,FOREIGN KEY(variable_id) REFERENCES variables(id) ON DELETE CASCADE,FOREIGN KEY(reference_id) REFERENCES `references`(id) ON DELETE SET NULL);
CREATE TABLE rules(id INT AUTO_INCREMENT PRIMARY KEY,code VARCHAR(10) NOT NULL UNIQUE,diagnosis ENUM('Rendah','Sedang','Tinggi','Sangat Tinggi') NOT NULL,priority INT NOT NULL,explanation TEXT,recommendation TEXT,reference_id INT,is_active TINYINT(1) DEFAULT 1,FOREIGN KEY(reference_id) REFERENCES `references`(id) ON DELETE SET NULL);
CREATE TABLE rule_conditions(id INT AUTO_INCREMENT PRIMARY KEY,rule_id INT NOT NULL,symptom_id INT NOT NULL,operator ENUM('AND') DEFAULT 'AND',UNIQUE(rule_id,symptom_id),FOREIGN KEY(rule_id) REFERENCES rules(id) ON DELETE CASCADE,FOREIGN KEY(symptom_id) REFERENCES symptoms(id) ON DELETE CASCADE);
CREATE TABLE consultations(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,location VARCHAR(150),notes TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE consultation_details(id INT AUTO_INCREMENT PRIMARY KEY,consultation_id INT NOT NULL,variable_id INT NOT NULL,symptom_id INT NOT NULL,FOREIGN KEY(consultation_id) REFERENCES consultations(id) ON DELETE CASCADE,FOREIGN KEY(variable_id) REFERENCES variables(id),FOREIGN KEY(symptom_id) REFERENCES symptoms(id));
CREATE TABLE diagnosis_results(id INT AUTO_INCREMENT PRIMARY KEY,consultation_id INT NOT NULL,rule_id INT NULL,diagnosis ENUM('Rendah','Sedang','Tinggi','Sangat Tinggi') NOT NULL,working_memory JSON,active_rules JSON,failed_rules JSON,inference_trace JSON,explanation TEXT,recommendation TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(consultation_id) REFERENCES consultations(id) ON DELETE CASCADE,FOREIGN KEY(rule_id) REFERENCES rules(id) ON DELETE SET NULL);
CREATE TABLE activity_logs(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT,action VARCHAR(80) NOT NULL,description TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL);
INSERT INTO roles VALUES(1,'admin','Administrator'),(2,'user','Pengguna');
INSERT INTO users(role_id,name,email,password) VALUES(1,'Administrator','admin@banjir.local','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.'),(2,'Pengguna','user@banjir.local','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.');
INSERT INTO `references` VALUES(1,'Laporan Akademik Sistem Pakar Potensi Banjir','Dokumen penelitian','Knowledge base dan rule base sesuai laporan akademik.');
INSERT INTO variables(code,name,description) VALUES('CH','Curah Hujan','Intensitas curah hujan'),('DH','Durasi Hujan','Lama hujan'),('KD','Kondisi Drainase','Kemampuan saluran air'),('KW','Ketinggian Wilayah','Elevasi wilayah'),('KS','Kedekatan Sungai','Jarak ke sungai'),('RB','Riwayat Banjir','Histori kejadian banjir'),('PD','Peringatan BMKG','Status peringatan dini');
INSERT INTO symptoms(variable_id,code,name,category,description,reference_id) VALUES
(1,'CH1','Curah hujan rendah','Rendah','Hujan ringan',1),(1,'CH2','Curah hujan sedang','Sedang','Hujan sedang',1),(1,'CH3','Curah hujan tinggi','Tinggi','Hujan lebat',1),(1,'CH4','Curah hujan sangat tinggi','Sangat Tinggi','Hujan ekstrem',1),
(2,'DH1','Durasi singkat','Rendah','Kurang dari durasi kritis',1),(2,'DH2','Durasi sedang','Sedang','Durasi cukup lama',1),(2,'DH3','Durasi lama','Tinggi','Hujan lama',1),(2,'DH4','Durasi sangat lama','Sangat Tinggi','Hujan sangat lama',1),
(3,'KD1','Drainase baik','Rendah','Aliran lancar',1),(3,'KD2','Drainase sedang','Sedang','Sebagian tersumbat',1),(3,'KD3','Drainase buruk','Tinggi','Banyak sumbatan',1),(3,'KD4','Drainase sangat buruk','Sangat Tinggi','Tidak berfungsi',1),
(4,'KW1','Wilayah tinggi','Rendah','Elevasi aman',1),(4,'KW2','Wilayah sedang','Sedang','Elevasi sedang',1),(4,'KW3','Wilayah rendah','Tinggi','Dataran rendah',1),
(5,'KS1','Jauh dari sungai','Rendah','Jarak aman',1),(5,'KS2','Cukup dekat sungai','Sedang','Dekat sungai',1),(5,'KS3','Sangat dekat sungai','Tinggi','Bantaran sungai',1),
(6,'RB1','Tidak pernah banjir','Rendah','Tidak ada histori',1),(6,'RB2','Jarang banjir','Sedang','Histori jarang',1),(6,'RB3','Sering banjir','Tinggi','Histori sering',1),
(7,'PD1','Tidak ada peringatan','Rendah','BMKG normal',1),(7,'PD2','Waspada','Sedang','BMKG waspada',1),(7,'PD3','Siaga','Tinggi','BMKG siaga',1),(7,'PD4','Awas','Sangat Tinggi','BMKG awas',1);
INSERT INTO rules(code,diagnosis,priority,explanation,recommendation,reference_id) VALUES
('R01','Rendah',1,'Mayoritas indikator rendah.','Tetap pantau cuaca.',1),('R02','Rendah',2,'Hujan rendah dengan drainase baik.','Jaga kebersihan drainase.',1),('R03','Rendah',3,'Wilayah tinggi dan jauh sungai.','Monitoring berkala.',1),('R04','Rendah',4,'Tidak ada peringatan dan riwayat aman.','Tetap waspada.',1),
('R05','Sedang',5,'Indikator hujan dan durasi sedang.','Bersihkan saluran air.',1),('R06','Sedang',6,'Drainase sedang dan dekat sungai.','Pantau tinggi muka air.',1),('R07','Sedang',7,'Riwayat jarang banjir disertai waspada.','Siapkan perlengkapan darurat.',1),('R08','Sedang',8,'Wilayah sedang dengan curah sedang.','Perkuat mitigasi rumah.',1),('R09','Sedang',9,'Durasi sedang dan drainase sedang.','Lapor jika ada genangan.',1),
('R10','Tinggi',10,'Hujan tinggi dan durasi lama.','Siapkan evakuasi.',1),('R11','Tinggi',11,'Drainase buruk dan wilayah rendah.','Amankan barang penting.',1),('R12','Tinggi',12,'Sangat dekat sungai dan sering banjir.','Pantau sungai intensif.',1),('R13','Tinggi',13,'Peringatan siaga dengan hujan tinggi.','Ikuti arahan petugas.',1),('R14','Tinggi',14,'Drainase buruk dan durasi lama.','Buka jalur air darurat.',1),('R15','Tinggi',15,'Wilayah rendah dekat sungai.','Siapkan titik kumpul.',1),
('R16','Sangat Tinggi',16,'Hujan ekstrem dan durasi sangat lama.','Segera bersiap evakuasi.',1),('R17','Sangat Tinggi',17,'Drainase tidak berfungsi dan wilayah rendah.','Koordinasi dengan BPBD.',1),('R18','Sangat Tinggi',18,'BMKG awas dan sering banjir.','Evakuasi kelompok rentan.',1),('R19','Sangat Tinggi',19,'Bantaran sungai dengan hujan ekstrem.','Hindari area sungai.',1),('R20','Sangat Tinggi',20,'Kombinasi ekstrem seluruh indikator utama.','Evakuasi bila diperintahkan.',1);
INSERT INTO rule_conditions(rule_id,symptom_id) VALUES
(1,1),(1,5),(1,9),(1,13),(1,16),(1,19),(1,22),(2,1),(2,9),(2,22),(3,13),(3,16),(3,19),(4,19),(4,22),
(5,2),(5,6),(5,10),(6,10),(6,17),(7,20),(7,23),(8,2),(8,14),(9,6),(9,10),
(10,3),(10,7),(11,11),(11,15),(12,18),(12,21),(13,3),(13,24),(14,11),(14,7),(15,15),(15,17),
(16,4),(16,8),(17,12),(17,15),(18,25),(18,21),(19,18),(19,4),(20,4),(20,8),(20,12),(20,15),(20,18),(20,21),(20,25);
